### ISSUE TITLE
Scottish beers, cat 14

### ISSUE THREAD

**Issue by stuartjcarter** [Rlshep/BJCP2015BeerStyles#15]
"Schilling" is not, and has never been, the correct spelling for any British coinage. It is the Germanic spelling. Referring to "Scottish schilling ales" is wrong, it should be "Scottish Shilling Ales".

**Comment by Rlshep** [comment]
This app uses the wording and spelling of the BJCP 2015 Guidelines. Please, submit any changes to bjcp.org and I will update the app with their revisions.
