### ISSUE TITLE
App for Android missing a style

### ISSUE THREAD

**Issue by scrmndmn** [Rlshep/BJCP2015BeerStyles#6]
Hello,

v1.0.0 of the Android Style Guidelines app is missing category 16D, Foreign Extra Stout.  Love the App, thank you!

Damien

**Comment by Rlshep** [comment]
Thanks for the heads up. Good catch!

**Comment by seth-k** [comment]
The perils of going from Word .doc -> export to HTML -> python script to XML. I've fixed the XML file in my project so a quick update should fix it.

**Comment by Rlshep** [comment]
Load updated xml to database and re-release 1.0.1
