### ISSUE TITLE
Crashes trying to view cider/perry styles

### ISSUE THREAD

**Issue by seth-k** [Rlshep/BJCP2015BeerStyles#7]
The app crashes when trying to view any of the cider/perry styles.  I got a capture of the relevant part of the dump. It looks like the app is crashing because it's trying to get the SRM (color) of the style and gets a null. The cider styles don't have SRM or IBU for stats, only the gravities and ABV.

 ![capture-bjcp15-error](https://cloud.githubusercontent.com/assets/11035665/10620167/6801ea7e-772e-11e5-8574-ed5b74ac754a.PNG).

**Comment by Rlshep** [comment]
How embarrassing. Fixed and pushed to Google Play.
